---
- name: reset ufw
  become: yes
  become_method: sudo
  ufw:
    state: reset
  when: ansible_distribution == "Ubuntu"
  tags:
    - ufw
    - security

- name: allow ssh ufw
  become: yes
  become_method: sudo
  ufw:
    rule: allow
    src: "{{ item }}"
    port: 22
    proto: tcp
  with_items:
    - "{{ sshd_admin_net }}"
  when: ansible_distribution == "Ubuntu"
  tags:
    - ufw
    - ssh
    - security

- name: enable ufw
  become: yes
  become_method: sudo
  ufw:
    state: enabled
    policy: deny
    logging: low
  when: ansible_distribution == "Ubuntu"
  tags:
    - ufw
    - security

- name: enable firewalld
  become: yes
  become_method: sudo
  service:
    name: firewalld
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"
  tags:
    - firewalld
    - security

- name: allow firewalld ssh
  become: yes
  become_method: sudo
  firewalld:
    service: ssh
    permanent: true
    state: enabled
  when: ansible_distribution == "CentOS"
  tags:
    - firewalld
    - security
...
