---
- name: disablenet.conf
  become: yes
  become_method: sudo
  file:
    state: touch
    path: /etc/modprobe.d/disablenet.conf
    owner: root
    group: root
    mode: 0644

- name: disable net modules
  become: yes
  become_method: sudo
  lineinfile:
    dest: /etc/modprobe.d/disablenet.conf
    line: "install {{ item }} /bin/true"
  with_items:
    - "{{ disable_net_modules }}"
  tags:
    - modprobe
    - security
...
