---
- name: apt update
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
    cache_valid_time: 1800
  when: ansible_distribution == "Ubuntu"
  tags:
    - apt
    - security

- name: apt upgrade
  become: yes
  become_method: sudo
  apt:
    upgrade: safe
  notify:
    - apt-get clean
    - apt-get autoremove
  when: ansible_distribution == "Ubuntu"
  tags:
    - apt
    - security

- name: set yum.conf gpgcheck
  become: yes
  become_method: sudo
  lineinfile:
    regexp: "^gpgcheck="
    line: "gpgcheck=1"
    dest: /etc/yum.conf
    mode: 0644
    state: present
    create: no
    backrefs: yes
  when: ansible_distribution == "CentOS"
  tags:
    - rc
    - security

- name: yum update
  become: yes
  become_method: sudo
  yum:
    name: '*'
    state: latest
    update_cache: yes
  notify:
    - yum clean
  when: ansible_distribution == "CentOS"
  tags:
    - yum
    - security
...
