---
- name: package installation
  become: yes
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
  with_items:
    - "{{ packages }}"
  tags:
    - apt
    - packages
    - security

- name: virtualbox package installation
  become: yes
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
  with_items:
    - virtualbox-guest-dkms
    - virtualbox-guest-utils
  when: ansible_bios_version == "VirtualBox" and ansible_distribution == "Ubuntu"
  tags:
    - apt
    - packages
    - virtualbox
    - security
...
