---
- name: ubuntu package installation
  become: yes
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
  with_items:
    - "{{ packages_ubuntu }}"
  when: ansible_distribution == "Ubuntu"
  tags:
    - apt
    - packages
    - security

- name: centos package installation
  become: yes
  become_method: sudo
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ packages_centos }}"
  when: ansible_distribution == "CentOS"
  tags:
    - yum
    - packages
    - security

- name: ubuntu package removal
  become: yes
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - "{{ packages_blacklist }}"
  when: ansible_distribution == "Ubuntu"
  tags:
    - apt
    - packages
    - security

- name: centos package removal
  become: yes
  become_method: sudo
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ packages_blacklist }}"
  when: ansible_distribution == "CentOS"
  tags:
    - yum
    - packages
    - security

- name: virtualbox package installation
  become: yes
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
  with_items:
    - virtualbox-guest-dkms
    - virtualbox-guest-utils
  when: ansible_bios_version == "VirtualBox" and ansible_distribution == "Ubuntu"
  tags:
    - apt
    - packages
    - virtualbox
    - security

- name: vmware package installation
  become: yes
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
  with_items:
    - open-vm-tools
  when: ansible_bios_version == "VMWare"
  tags:
    - apt
    - yum
    - packages
    - vmware
    - security
...
