---
# CCE-27407-6

- name: audit.rules
  become: 'yes'
  template:
    src: etc/audit/rules.d/hardening.rules.j2
    dest: /etc/audit/rules.d/hardening.rules
    backup: 'yes'
    mode: 0600
    owner: root
    group: root
  notify:
    - generate auditd
    - restart auditd
  tags:
    - auditd
    - audit.rules
    - security

- name: set audit grub cmdline
  become: 'yes'
  lineinfile:
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="{{ grub_cmdline }}"'
    dest: /etc/default/grub
    state: present
  when: ansible_os_family == "Debian"
  tags:
    - auditd
    - grub
    - security
...
