---
- name: rkhunter
  become: yes
  become_method: sudo
  template:
    src: rkhunter.j2
    dest: /etc/default/rkhunter
    backup: yes
    mode: 0644
    owner: root
    group: root
  when: ansible_distribution == "Ubuntu"
  notify:
    - rkhunter propupd
  tags:
    - packages
    - rkhunter
    - security
...
