---
- name: restrict compiler access
  become: 'yes'
  file:
    owner: root
    group: root
    mode: 0750
    state: file
    follow: 'yes'
    path: "{{ item }}"
  register: output
  failed_when: "output.failed and not 'absent' in output.msg"
  with_items:
    - "{{ compilers }}"
  tags:
    - suid
...
