---
- name: remove cron.deny and at.deny
  become: 'yes'
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/at.deny
    - /etc/cron.deny
  tags:
    - at
    - cron

- name: clean cron and at
  become: 'yes'
  lineinfile:
    path: "{{ item }}"
    regexp: "^(?!root).*$"
    state: absent
  with_items:
    - /etc/at.allow
    - /etc/cron.allow
  tags:
    - at
    - cron

- name: allow root cron and at
  become: 'yes'
  lineinfile:
    path: "{{ item }}"
    line: "root"
    mode: 0600
    state: present
    create: 'yes'
  with_items:
    - /etc/at.allow
    - /etc/cron.allow
  tags:
    - at
    - cron

- name: mask atd
  become: 'yes'
  systemd:
    name: atd
    masked: 'yes'
    enabled: 'no'
    state: stopped
  register: mask_atd
  failed_when: mask_atd is not success and not "Could not find the requested service" in mask_atd.msg
  tags:
    - at
    - systemd

- name: cron permissions
  become: 'yes'
  file:
    path: "{{ item }}"
    mode: 0700
    owner: root
    group: root
  with_items:
    - /etc/cron.d
    - /etc/cron.daily
    - /etc/cron.hourly
    - /etc/cron.weekly
    - /etc/cron.monthly
  tags:
    - cron

- name: crontab permissions
  become: 'yes'
  file:
    path: /etc/crontab
    mode: 0600
    owner: root
    group: root
  tags:
    - cron
    - crontab
...
