---
- name: disable misc kernel modules
  become: 'yes'
  lineinfile:
    dest: /etc/modprobe.d/disablemod.conf
    line: "install {{ item }} /bin/true"
    mode: 0644
    owner: root
    group: root
    state: present
    create: 'yes'
  with_items:
    - "{{ misc_modules_blocklist }}"
  tags:
    - modprobe
    - CCE-80832-9
    - CCE-82005-0
    - CCE-82059-7
    - CIS-UBUNTU2004-1.1.24
    - M1034
    - M1038
    - M1042
...
