---
- name: disable file system kernel modules
  become: 'yes'
  lineinfile:
    dest: /etc/modprobe.d/disablefs.conf
    line: "install {{ item }} /bin/true"
    mode: 0644
    owner: root
    group: root
    state: present
    create: 'yes'
  with_items:
    - "{{ fs_modules_blocklist }}"
  when: not booted_with_efi
  tags:
    - modprobe

- name: dont disable vfat file system kernel modules if efi
  become: 'yes'
  lineinfile:
    dest: /etc/modprobe.d/disablefs.conf
    line: "install {{ item }} /bin/true"
    mode: 0644
    owner: root
    group: root
    state: present
    create: 'yes'
  with_items:
    - "{{ fs_modules_blocklist | reject('search','vfat') | list }}"
  when: booted_with_efi
  tags:
    - modprobe
...
