---
- name: Reboot if required
  become: true
  ansible.builtin.setup: ~
  notify:
    - Reboot node
  when: ansible_distribution == "Ubuntu" and ansible_local.reboot.required and
        reboot_ubuntu
  tags:
    - reboot
    - ubuntu
...
