---
- name: Set Debian ipv6.disable GRUB cmdline
  become: true
  ansible.builtin.lineinfile:
    line: GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX ipv6.disable=1"
    dest: /etc/default/grub.d/99-hardening-ipv6.cfg
    state: present
    create: true
    mode: "0640"
    owner: root
    group: root
  when: ansible_os_family == "Debian"
  notify:
    - Update GRUB
  tags:
    - ipv6
    - CIS-UBUNTU2004-3.1.1

- name: Set RedHat ipv6.disable GRUB cmdline
  become: true
  ansible.builtin.command:
    cmd: grubby --update-kernel=ALL --args="ipv6.disable=1"
  register: grubby_update_kernel
  when: ansible_os_family == "RedHat"
  changed_when: grubby_update_kernel.rc != 0
  failed_when: grubby_update_kernel.rc != 0
  tags:
    - ipv6

- name: Template sysctl file with settings to disabled ipv6 for the running machine
  become: true
  ansible.builtin.template:
    src: '{{ sysctl_ipv6_config_template }}'
    dest: '{{ sysctl_conf_dir }}/zz-002-ipv6-hardening.conf'
    mode: "0755"
    owner: root
    group: root
    backup: false
  when: system_has_ipv6
  notify:
    - Restart sysctl
  tags:
    - ipv6

- name: Make sure we delete the ipv6 sysctl file if this machine doesn't support ipv6
  become: true
  ansible.builtin.file:
    path: '{{ sysctl_conf_dir }}/zz-002-ipv6-hardening.conf'
    state: absent
  when: not system_has_ipv6
  notify:
    - Restart sysctl
