---
- name: stat issue file
  stat:
    path: "{{ item }}"
  register: issue_files
  with_items:
    - /etc/issue
    - /etc/issue.net
  tags:
    - motd

- name: remove issue and issue.net
  become: 'yes'
  file:
    path: "{{ item.stat.path }}"
    state: absent
  when: item.stat.exists and not item.stat.islnk
  with_items:
    - "{{ issue_files.results }}"
  tags:
    - motd

- name: add notice
  become: 'yes'
  template:
    src: etc/motd.j2
    dest: /etc/motd
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  tags:
    - motd

- name: link issue to motd
  become: 'yes'
  file:
    src: /etc/motd
    dest: "{{ item }}"
    owner: root
    group: root
    state: link
  with_items:
    - /etc/issue
    - /etc/issue.net
  tags:
    - motd
...
