---
- name: configure systemd resolved.conf
  become: true
  ansible.builtin.template:
    src: etc/systemd/resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  notify:
    - reload systemd
  tags:
    - resolved
    - systemd
    - CCE-84049-6

- name: add nameserver to resolv.conf
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/resolv.conf
    line: "nameserver {{ item }}"
    mode: 0644
    owner: root
    group: root
    state: present
  with_items: "{{ dns | split }}"
  when: ansible_os_family == "RedHat"
...
