---
- name: sudo use_pty
  become: true
  ansible.builtin.lineinfile:
    line: "Defaults use_pty"
    dest: /etc/sudoers.d/011_use_pty
    mode: 0440
    state: present
    create: true
  tags:
    - sudo
    - CIS-UBUNTU2004-5.2.2

- name: sudo configure logfile
  become: true
  ansible.builtin.lineinfile:
    line: 'Defaults logfile="/var/log/sudo.log"'
    dest: /etc/sudoers.d/012_logfile
    mode: 0440
    state: present
    create: true
  tags:
    - sudo
    - CIS-UBUNTU2004-5.2.3

- name: sudo disable pwfeedback
  become: true
  ansible.builtin.lineinfile:
    line: "Defaults !pwfeedback"
    dest: /etc/sudoers.d/013_pwfeedback
    mode: 0440
    state: present
    create: true
  tags:
    - sudo

- name: sudo disable visiblepw
  become: true
  ansible.builtin.lineinfile:
    line: "Defaults !visiblepw"
    dest: /etc/sudoers.d/014_visiblepw
    mode: 0440
    state: present
    create: true
  tags:
    - sudo

- name: remove inconsistently named sudoer file
  become: true
  ansible.builtin.file:
    path: /etc/sudoers.d/15_timeout
    state: absent

- name: sudo passwd_timeout
  become: true
  ansible.builtin.lineinfile:
    line: "Defaults passwd_timeout=1"
    dest: /etc/sudoers.d/015_passwdtimeout
    mode: 0440
    state: present
    create: true
  tags:
    - sudo

- name: sudo timestamp_timeout
  become: true
  ansible.builtin.lineinfile:
    line: "Defaults timestamp_timeout=5"
    dest: /etc/sudoers.d/016_timestamptimeout
    mode: 0440
    state: present
    create: true
  tags:
    - sudo

- name: sudo timestamp_type
  become: true
  ansible.builtin.lineinfile:
    line: "Defaults timestamp_type=tty"
    dest: /etc/sudoers.d/017_timestamptype
    mode: 0440
    state: present
    create: true
  tags:
    - sudo
    - M1028

- name: create su group sugroup
  become: true
  ansible.builtin.group:
    name: sugroup
    state: present
  tags:
    - sudo
    - CIS-UBUNTU2004-5.7

- name: configure su group
  become: true
  ansible.builtin.lineinfile:
    line: "auth required pam_wheel.so use_uid group=sugroup"
    dest: /etc/pam.d/su
    mode: 0644
    state: present
    create: true
  tags:
    - sudo
    - CIS-UBUNTU2004-5.7
...
