---
- name: remove suid/sgid
  become: 'yes'
  file:
    path: "{{ item }}"
    mode: 'a-s'
    state: file
    follow: 'yes'
  register: output
  failed_when: "output.failed and output.state != 'absent'"
  with_items:
    - "{{ suid_sgid_blocklist }}"
  tags:
    - suid
...
