---
- name: register binaries in SUID/SGID blocklist
  become: 'yes'
  find:
    paths: ['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin', '/snap/bin']
    patterns: "{{ suid_sgid_blocklist }}"
    recurse: 'yes'
  register: suid

- name: remove suid/sgid
  become: 'yes'
  file:
    path: "{{ item.path }}"
    mode: 'a-s'
    state: file
    follow: 'yes'
  with_items:
    - "{{ suid.files }}"
  tags:
    - suid
...
