---
dependency:
  enabled: false
driver:
  name: vagrant
  provider:
    name: virtualbox
  provider_options:
    linked_clone: false
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml
  log: true
  inventory:
    host_vars:
      centos:
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: "vagrant sudo"
      centos-stream:
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: "vagrant sudo"
platforms:
  - name: centos
    box: bento/centos-8
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
  - name: centos-stream
    box: "centos-stream/20210210"
    box_url: "https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-Vagrant-8-20210210.0.x86_64.vagrant-virtualbox.box"
    box_download_checksum: "4ba18cc4bde5f634580b0a6142f328c84d594d75c4775e87f9a4cb26714ad423"
    box_download_checksum_type: "sha256"
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
verifier:
  name: ansible
lint: |
  set -e
  ansible-lint --exclude .git --exclude .github --exclude tests/
  yamllint -d "{extends: default, ignore: .git*, rules: {line-length: {max: 120, level: warning}}}" .
scenario:
  name: centos
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
