---
- name: restart auditd debian
  become: true
  ansible.builtin.service:
    name: auditd
    state: restarted
  when: ansible_os_family == "Debian"
  tags:
    - CCE-80872-5

# https://github.com/ansible/ansible/issues/22171
- name: restart auditd redhat  # noqa command-instead-of-module
  become: true
  ansible.builtin.command: service auditd restart
  when: ansible_os_family == "RedHat"
  tags:
    - CCE-80872-5

- name: generate auditd
  become: true
  ansible.builtin.command: augenrules

- name: restart sysctl
  become: true
  ansible.builtin.service:
    name: systemd-sysctl
    state: restarted

- name: reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: 'yes'

- name: rkhunter propupd
  become: true
  ansible.builtin.command: rkhunter --propupd

- name: enable aidecheck
  become: true
  ansible.builtin.systemd:
    name: aidecheck.timer
    enabled: 'yes'
    state: started

- name: disable aidecheck
  become: true
  ansible.builtin.systemd:
    name: aidecheck.timer
    state: stopped
    enabled: 'no'

- name: mask aidecheck
  become: true
  ansible.builtin.systemd:
    name: aidecheck.timer
    masked: 'yes'
    stated: stopped
    enabled: 'no'

- name: restart sshd
  become: true
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: restart postfix
  become: true
  ansible.builtin.service:
    name: postfix
    state: restarted

- name: apt-get autoremove
  become: true
  ansible.builtin.apt:
    autoremove: 'yes'

- name: apt-get clean
  become: true
  ansible.builtin.apt:
    autoclean: 'yes'

- name: mask apport
  become: true
  ansible.builtin.systemd:
    name: apport.service
    masked: 'yes'
    enabled: 'no'
    state: stopped

- name: mask motdnews timer
  become: true
  ansible.builtin.systemd:
    name: motd-news.timer
    masked: 'yes'
    enabled: 'no'
    state: stopped

- name: mask motdnews service
  become: true
  ansible.builtin.systemd:
    name: motd-news.service
    masked: 'yes'
    enabled: 'no'
    state: stopped

- name: dnf autoremove
  ansible.builtin.dnf:
    autoremove: 'yes'
  when: ansible_os_family == "RedHat"
  tags:
    - dnf
    - packages

- name: enable haveged
  become: true
  ansible.builtin.systemd:
    name: haveged
    enabled: 'yes'
    state: started

- name: reboot node
  become: true
  ansible.builtin.reboot:
    pre_reboot_delay: "{{ 3600 | random(start=1) }}"

- name: update cracklib debian
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  become: true
  ansible.builtin.command: update-cracklib
  when: ansible_os_family == "Debian"

- name: update cracklib redhat
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  become: true
  ansible.builtin.command: create-cracklib-dict /usr/share/dict/*
  when: ansible_os_family == "RedHat"

- name: update grub
  become: true
  ansible.builtin.command: update-grub

- name: update grub2
  become: true
  ansible.builtin.command: grub2-mkconfig
...
