---
dependency:
  enabled: false
driver:
  name: vagrant
  provider:
    name: VBox
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  log: true
  inventory:
    host_vars:
      buster:
        ansible_python_interpreter: "/usr/bin/python3"
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: "vagrant sudo"
      centos:
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: "vagrant sudo"
      centos-stream:
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: "vagrant sudo"
      focal:
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: "vagrant sudo"
      groovy:
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: "vagrant sudo"
platforms:
  - name: buster
    box: bento/debian-10
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
  - name: centos
    provider_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
    box: bento/centos-8
  - name: centos-stream
    provider_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
    box: "centos-stream/20201019"
    box_url: "https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-Vagrant-8-20201019.1.x86_64.vagrant-virtualbox.box"
  - name: focal
    provider_options:
      nic_model_type: '"Am79C973"'
      vm.boot_timeout: 600
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
    box: bento/ubuntu-20.04
  - name: groovy
    provider_options:
      nic_model_type: '"Am79C973"'
      vm.boot_timeout: 600
    config_options:
      synced_folder: false
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uart1', '0x3F8', '4']"
      - "customize ['modifyvm', :id, '--uartmode1', 'file', File::NULL]"
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 2048
    box: ubuntu/groovy64
verifier:
  name: ansible
lint: |
  set -e
  ansible-lint .
  yamllint -d "{extends: default, rules: {line-length: {level: warning}}}" .
scenario:
  name: default
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
