---
dependency:
  enabled: False
driver:
  name: vagrant
  provider:
    name: VBox
provisioner:
  name: ansible
  inventory:
    host_vars:
      bionic:
        random_ack_limit: 10000
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: "vagrant sudo"
      buster:
        ansible_python_interpreter: "/usr/bin/python3"
        random_ack_limit: 10000
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: "vagrant sudo"
      fedora:
        random_ack_limit: 10000
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: "vagrant sudo"
      focal:
        random_ack_limit: 10000
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: "vagrant sudo"
platforms:
  - name: bionic
    box: ubuntu/bionic64
  - name: buster
    box: bento/debian-10
  - name: focal
    box: bento/ubuntu-20.04
# The following platforms fail due to molecule or vagrant issues
#  - name: centos
#    box: centos/8
#  - name: fedora
#    box: bento/fedora-32
verifier:
  name: ansible
lint: |
  set -e
  ansible-lint .
  yamllint -d "{extends: default, rules: {line-length: {level: warning}}}" .
scenario:
  name: default
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence disabled due to firewall resets, random sysctl settings et al
    - side_effect
    - verify
    - cleanup
    - destroy
