---
- name: Verify
  hosts: all
  any_errors_fatal: true
  vars:
    auditd_action_mail_acct: root
    auditd_admin_space_left_action: suspend
    auditd_max_log_file_action: keep_logs
    auditd_mode: 1
    auditd_space_left_action: email
    sshd_allow_agent_forwarding: 'no'
    sshd_allow_tcp_forwarding: 'no'
    sshd_authentication_methods: any
    sshd_banner: /etc/issue.net
    sshd_challenge_response_authentication: 'no'
    sshd_ciphers: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes256-ctr
    sshd_client_alive_count_max: 3
    sshd_client_alive_interval: 200
    sshd_compression: 'no'
    sshd_gssapi_authentication: 'no'
    sshd_hostbased_authentication: 'no'
    sshd_ignore_user_known_hosts: 'yes'
    sshd_kerberos_authentication: 'no'
    sshd_kex_algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256
    sshd_log_level: VERBOSE
    sshd_login_grace_time: 20
    sshd_macs: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256
    sshd_max_auth_tries: 3
    sshd_max_sessions: 3
    sshd_max_startups: 10:30:60
    sshd_password_authentication: 'no'
    sshd_permit_empty_passwords: 'no'
    sshd_permit_root_login: 'no'
    sshd_permit_user_environment: 'no'
    sshd_port: 22
    sshd_print_last_log: 'yes'
    sshd_print_motd: 'no'
    sshd_rekey_limit: 512M 1h
    sshd_strict_modes: 'yes'
    sshd_subsystem: sftp internal-sftp
    sshd_tcp_keep_alive: 'no'
    sshd_use_dns: 'no'
    sshd_use_pam: 'yes'
    sshd_x11_forwarding: 'no'

  tasks:
    - name: verify auditd configuration
      become: 'yes'
      shell: grep "^{{ item }}$" /etc/audit/auditd.conf
      register: auditd_conf
      failed_when: auditd_conf.rc != 0
      with_items:
        - action_mail_acct = {{ auditd_action_mail_acct }}
        - admin_space_left_action = {{ auditd_admin_space_left_action }}
        - max_log_file_action = {{ auditd_max_log_file_action }}
        - space_left_action = {{ auditd_space_left_action }}

    - name: verify postfix configuration
      become: 'yes'
      shell: grep -c "^{{ item }}$" /etc/postfix/main.cf
      register: auditd_conf
      failed_when: auditd_conf.rc != 0 and auditd_conf.stdout != "1"
      with_items:
        - disable_vrfy_command = yes
        - inet_interfaces = loopback-only
        - smtpd_banner = \"\\\\\$myhostname - ESMTP\"
        - smtpd_client_restrictions = permit_mynetworks,reject

    - name: stat /etc/ssh/sshd_config
      stat:
        path: '/etc/ssh/sshd_config'
      register: perm_sshd_config

    - name: assert /etc/ssh/sshd_config permissions
      assert:
        that:
          - perm_sshd_config.stat.mode == "0600"
        success_msg: "{{ perm_sshd_config.stat.path }} has correct permissions: {{ perm_sshd_config.stat.mode }}"
        fail_msg: "{{ perm_sshd_config.stat.path }} permissions are incorrect: {{ perm_sshd_config.stat.mode }}"

    - name: verify sshd_config PermitRootLogin configuration
      become: 'yes'
      shell: grep "^{{ item }}$" /etc/ssh/sshd_config
      register: sshd_config
      failed_when: sshd_config.rc == 0
      with_items:
        - PermitRootLogin yes

    - name: verify sshd_config configuration
      become: 'yes'
      shell: grep "^{{ item }}$" /etc/ssh/sshd_config
      register: sshd_config
      failed_when: sshd_config.rc != 0
      with_items:
        - AllowGroups vagrant sudo
        - AllowAgentForwarding {{ sshd_allow_agent_forwarding }}
        - AllowTcpForwarding {{ sshd_allow_tcp_forwarding }}
        - AuthenticationMethods {{ sshd_authentication_methods }}
        - Banner {{ sshd_banner }}
        - ChallengeResponseAuthentication {{ sshd_challenge_response_authentication }}
        - Ciphers {{ sshd_ciphers }}
        - ClientAliveCountMax {{ sshd_client_alive_count_max|int }}
        - ClientAliveInterval {{ sshd_client_alive_interval|int }}
        - Compression {{ sshd_compression }}
        - GSSAPIAuthentication {{ sshd_gssapi_authentication }}
        - HostbasedAuthentication {{ sshd_hostbased_authentication }}
        - IgnoreUserKnownHosts {{ sshd_ignore_user_known_hosts }}
        - KerberosAuthentication {{ sshd_kerberos_authentication }}
        - KexAlgorithms {{ sshd_kex_algorithms }}
        - LogLevel {{ sshd_log_level }}
        - LoginGraceTime {{ sshd_login_grace_time|int }}
        - Macs {{ sshd_macs }}
        - MaxAuthTries {{ sshd_max_auth_tries|int }}
        - MaxSessions {{ sshd_max_sessions|int }}
        - MaxStartups {{ sshd_max_startups }}
        - PasswordAuthentication {{ sshd_password_authentication }}
        - PermitEmptyPasswords {{ sshd_permit_empty_passwords }}
        - PermitRootLogin {{ sshd_permit_root_login }}
        - PermitUserEnvironment {{ sshd_permit_user_environment }}
        - Port {{ sshd_port|int }}
        - PrintLastLog {{ sshd_print_last_log }}
        - PrintMotd {{ sshd_print_motd }}
        - RekeyLimit {{ sshd_rekey_limit }}
        - StrictModes {{ sshd_strict_modes }}
        - Subsystem {{ sshd_subsystem }}
        - TCPKeepAlive {{ sshd_tcp_keep_alive }}
        - UseDNS {{ sshd_use_dns }}
        - UsePAM {{ sshd_use_pam }}
        - X11Forwarding {{ sshd_x11_forwarding }}
...
