---
dependency:
  enabled: false
driver:
  name: vagrant
  provider:
    name: virtualbox
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml
  log: true
  inventory:
    host_vars:
      focal:
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: "vagrant sudo"
      focalefi:
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: "vagrant sudo"
      hirsute:
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: "vagrant sudo"
      impish:
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: "vagrant sudo"
platforms:
  - name: focal
    box: bento/ubuntu-20.04
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
  - name: focalefi
    box: konstruktoid/focal-hardened
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
  - name: hirsute
    box: ubuntu/hirsute64
    config_options:
      vm.boot_timeout: 600
      synced_folder: false
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uart1', '0x3F8', '4']"
      - "customize ['modifyvm', :id, '--uartmode1', 'file', File::NULL]"
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
  - name: impish
    box: "impish/20210611"
    box_url: "https://cloud-images.ubuntu.com/impish/20210705/impish-server-cloudimg-amd64-vagrant.box"
    box_download_checksum: "6d25ec2c61273af034c4a4341b6355e2ed761cff5209c7917698cbbd736116af"
    box_download_checksum_type: "sha256"
    config_options:
      vm.boot_timeout: 600
      synced_folder: false
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uart1', '0x3F8', '4']"
      - "customize ['modifyvm', :id, '--uartmode1', 'file', File::NULL]"
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
verifier:
  name: ansible
lint: |
  set -e
  ansible-lint --exclude .git --exclude .github --exclude tests/
  yamllint -d "{extends: default, ignore: .git*, rules: {line-length: {max: 120, level: warning}}}" .
scenario:
  name: ubuntu
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
