on: push
name: New workflow
jobs:
  konstruktoidYAMLLint:
    name: Konstruktoid YAML lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Konstruktoid YAML lint
        uses: ./action-lint
